#!/bin/sh

if [ $# -ne 1 ]
then
  echo "mk-tex-code: usage: file" 1>&2
  exit 111
fi

title=`head -n 1 "$1"` || exit 1
cat <<EOF
\ss

\def\headcmd {
  {\tfd \pagenumber / \totalnumberofpages}
}

\setupheadertexts[${title}][chapter]
% \setupheader[][before=\headcmd]
EOF
